import { PaymentItem } from "../types";
import { formatCurrency } from "./calculations";

/**
 * Format Date to iCalendar UTC/Local string (YYYYMMDDTHHMMSS)
 */
function formatIcsDateTime(dateStr: string, timeStr?: string, addHours = 0): string {
  const date = new Date(`${dateStr}T${timeStr || "09:00"}:00`);
  date.setHours(date.getHours() + addHours);
  const pad = (value: number) => String(value).padStart(2, "0");
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}T${pad(date.getHours())}${pad(date.getMinutes())}00`;
}

/**
 * Generates RFC 5545 compliant iCalendar (.ics) content for a single payment item.
 * Supports iOS Apple Calendar, Android native device calendar, Samsung Calendar, Outlook, etc.
 */
export function generateItemIcs(item: PaymentItem): string {
  const dtStart = formatIcsDateTime(item.date, item.time);
  const dtEnd = formatIcsDateTime(item.date, item.time, 1);
  const nowUtc = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
  const uid = `mmv-item-${item.id}@mmvhub.app`;

  const summary = `[MMV Hub] ${item.name} (${formatCurrency(item.price, item.currency)})`;
  const descriptionLines = [
    `Payment reminder generated by MMV Hub`,
    `Service / Item: ${item.name}`,
    `Amount: ${formatCurrency(item.price, item.currency)}`,
    `Type: ${item.type === "subscription" ? "Subscription" : item.type === "bill" ? "Recurring Bill" : "One-Time Purchase"}`,
    `Due Date: ${item.date}${item.time ? " at " + item.time : ""}`,
    item.notes ? `Notes: ${item.notes}` : "",
  ].filter(Boolean);

  const description = descriptionLines.join("\\n");

  // Recurrence rule
  let rrule = "";
  if (item.type === "subscription" || item.type === "bill") {
    const unit = item.frequency?.unit || "months";
    const interval = item.frequency?.interval || 1;
    if (unit === "days") {
      rrule = `RRULE:FREQ=DAILY;INTERVAL=${interval}\r\n`;
    } else if (unit === "weeks") {
      rrule = `RRULE:FREQ=WEEKLY;INTERVAL=${interval}\r\n`;
    } else if (unit === "years") {
      rrule = `RRULE:FREQ=YEARLY;INTERVAL=${interval}\r\n`;
    } else {
      rrule = `RRULE:FREQ=MONTHLY;INTERVAL=${interval}\r\n`;
    }
  }

  // 1-day before alarm, 2-hour before alarm, and at due time alarm for phone
  const alarms = `BEGIN:VALARM\r
ACTION:DISPLAY\r
DESCRIPTION:Reminder: ${item.name} is due tomorrow\r
TRIGGER:-P1D\r
END:VALARM\r
BEGIN:VALARM\r
ACTION:DISPLAY\r
DESCRIPTION:Payment Due Soon: ${item.name} (${formatCurrency(item.price, item.currency)})\r
TRIGGER:-PT2H\r
END:VALARM\r
BEGIN:VALARM\r
ACTION:DISPLAY\r
DESCRIPTION:Payment Due Now: ${item.name}\r
TRIGGER:-PT0M\r
END:VALARM\r
`;

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//MMV Hub//Phone Calendar Export//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:MMV Hub Reminders",
    "BEGIN:VEVENT",
    `UID:${uid}`,
    `DTSTAMP:${nowUtc}`,
    `DTSTART:${dtStart}`,
    `DTEND:${dtEnd}`,
    rrule ? rrule.trim() : null,
    `SUMMARY:${summary}`,
    `DESCRIPTION:${description}`,
    "STATUS:CONFIRMED",
    alarms.trim(),
    "END:VEVENT",
    "END:VCALENDAR",
  ]
    .filter(Boolean)
    .join("\r\n");
}

/**
 * Downloads / triggers native phone calendar import for a single payment item.
 * On iPhone / iPad / Android, tapping opens the native calendar app immediately.
 */
export function downloadPhoneCalendarEvent(item: PaymentItem): void {
  const icsData = generateItemIcs(item);
  const blob = new Blob([icsData], { type: "text/calendar;charset=utf-8" });
  const filename = `${item.name.replace(/[^a-zA-Z0-9_-]/g, "_")}_reminder.ics`;

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/**
 * Exports multiple payment items into a single .ics calendar file for batch phone import.
 */
export function downloadAllItemsPhoneCalendar(items: PaymentItem[]): number {
  const eligibleItems = items.filter(
    (i) => i.date && i.manualStatus !== "paid" && i.manualStatus !== "skipped"
  );
  if (eligibleItems.length === 0) return 0;

  const nowUtc = new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
  const events = eligibleItems.map((item) => {
    const dtStart = formatIcsDateTime(item.date, item.time);
    const dtEnd = formatIcsDateTime(item.date, item.time, 1);
    const uid = `mmv-item-${item.id}@mmvhub.app`;
    const summary = `[MMV Hub] ${item.name} (${formatCurrency(item.price, item.currency)})`;
    const desc = `Amount: ${formatCurrency(item.price, item.currency)}\\nType: ${item.type}\\nDue: ${item.date}${item.notes ? "\\nNotes: " + item.notes : ""}`;

    let rrule = "";
    if (item.type === "subscription" || item.type === "bill") {
      const unit = item.frequency?.unit || "months";
      const interval = item.frequency?.interval || 1;
      if (unit === "days") rrule = `RRULE:FREQ=DAILY;INTERVAL=${interval}\r\n`;
      else if (unit === "weeks") rrule = `RRULE:FREQ=WEEKLY;INTERVAL=${interval}\r\n`;
      else if (unit === "years") rrule = `RRULE:FREQ=YEARLY;INTERVAL=${interval}\r\n`;
      else rrule = `RRULE:FREQ=MONTHLY;INTERVAL=${interval}\r\n`;
    }

    return [
      "BEGIN:VEVENT",
      `UID:${uid}`,
      `DTSTAMP:${nowUtc}`,
      `DTSTART:${dtStart}`,
      `DTEND:${dtEnd}`,
      rrule ? rrule.trim() : null,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${desc}`,
      "STATUS:CONFIRMED",
      "BEGIN:VALARM",
      "ACTION:DISPLAY",
      `DESCRIPTION:Reminder: ${item.name} payment due`,
      "TRIGGER:-P1D",
      "END:VALARM",
      "BEGIN:VALARM",
      "ACTION:DISPLAY",
      `DESCRIPTION:Payment Due Now: ${item.name}`,
      "TRIGGER:-PT0M",
      "END:VALARM",
      "END:VEVENT",
    ]
      .filter(Boolean)
      .join("\r\n");
  });

  const icsFull = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//MMV Hub//Phone Calendar Export//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:MMV Hub All Reminders",
    ...events,
    "END:VCALENDAR",
  ].join("\r\n");

  const blob = new Blob([icsFull], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", "mmv_hub_reminders.ics");
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1500);

  return eligibleItems.length;
}

/**
 * Returns a 100% reliable zero-auth web link to add event directly to Google Calendar
 * without requiring Firebase auth or popup permissions.
 */
export function getGoogleCalendarWebLink(item: PaymentItem): string {
  const title = encodeURIComponent(`[MMV Hub] ${item.name} (${formatCurrency(item.price, item.currency)})`);
  const details = encodeURIComponent(
    `Payment reminder generated by MMV Hub\nAmount: ${formatCurrency(item.price, item.currency)}\nDue: ${item.date}${item.notes ? "\nNotes: " + item.notes : ""}`
  );
  const dates = `${formatIcsDateTime(item.date, item.time)}/${formatIcsDateTime(item.date, item.time, 1)}`;

  let recur = "";
  if (item.type === "subscription" || item.type === "bill") {
    recur = "&recur=RRULE:FREQ=MONTHLY";
  }

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${details}${recur}`;
}
